version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    networks:
      - mern

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    networks:
      - mern
    depends_on:
      - backend

networks:
  mern:
